# Generated by Django 4.1.2 on 2022-10-29 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания комментария'),
        ),
    ]
