# Generated by Django 4.1.2 on 2022-10-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='comment_status',
            field=models.CharField(default='Отправлена', max_length=50, verbose_name='Комментарий к статусу'),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус заявки'),
        ),
    ]
