# Generated by Django 4.1.2 on 2022-10-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='when',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.CharField(blank=True, default='', max_length=9999, verbose_name='Участники чата'),
        ),
    ]
