# Generated by Django 4.1.2 on 2022-10-30 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_when_remove_chat_members_chat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='when',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата отправки'),
        ),
    ]
